Repository ChoiKang-TEAM/Meal-Guard, pull requests merged in 2023-08, with the labels that each got.

#74 Fe feat/sign up UI
  client/src/common/constants.ts
  client/src/common/models.ts
  client/src/components/sign-up/PrivacyPolicy.vue
  client/src/pages/SignUp.vue
Labels: FE

#75 Fe feat/sign up UI
  client/src/components/sign-up/PrivacyPolicy.vue
Labels: FE

#76 Fe feat/sign up UI
  client/src/components/sign-up/PrivacyPolicy.vue
  client/src/pages/SignUp.vue
  client/src/stores/auth-store.ts
Labels: FE

#78 Fe feat/sign up UI
  client/src/common/constants.ts
  client/src/common/regexs.ts
  client/src/components/sign-up/IdentityVerify.vue
  client/src/components/sign-up/PrivacyPolicy.vue
  client/src/css/common.scss
  client/src/pages/SignUp.vue
Labels: FE

#79 * 회원가입 3단계 양식 작성 중
  client/src/common/utils.ts
  client/src/components/sign-up/IdentityVerify.vue
  client/src/components/sign-up/InformationEnter.vue
  client/src/css/common.scss
  client/src/pages/recipe/RecipeDetail.vue
Labels: FE

#80 * 회원 정보 입력 구현 폼
  client/src/components/sign-up/IdentityVerify.vue
  client/src/components/sign-up/InformationEnter.vue
  client/src/components/sign-up/PrivacyPolicy.vue
  client/src/stores/auth-store.ts
Labels: FE

#81 Fe feat/sign up UI
  client/src/components/recipe/RecipeBlogCard.vue
  client/src/components/recipe/RecipeTableDialog.vue
  client/src/components/sign-up/IdentityVerify.vue
  client/src/components/sign-up/InformationEnter.vue
  client/src/composables/interceptor.ts
Labels: FE

#82 Fe feat/sign up UI
  client/package.json
  client/src/components/sign-up/InformationEnter.vue
  client/src/css/common.scss
  client/yarn.lock
Labels: FE

#83 * 유저 아이디 체크 관련 graphQL api 작성
  sub-server-graphql/src/member/user/user.resolver.ts
  sub-server-graphql/src/member/user/user.service.ts
Labels: BE

#84 Fix: 성능 향상
  server/src/main/java/choikang/MealGuard/recipe/entity/Favorite.java
Labels: Development, BE

#85 * 아이디 유효성 검사 작업 완료
  client/src/components/sign-up/InformationEnter.vue
  client/src/graphql/dto/member-user-input.ts
  client/src/graphql/member-user.ts
  client/src/stores/auth-store.ts
  client/src/stores/member-user-store.ts
Labels: FE

#86 Fix: 날씨 버그 수정
  server/src/main/java/choikang/MealGuard/weather/service/WeatherApiService.java
Labels: BE

#87 Fe feat/sign up UI
  client/src/common/models.ts
  client/src/common/regexs.ts
  client/src/components/sign-up/InformationEnter.vue
  client/src/components/sign-up/PreferredFoodCheck.vue
  client/src/css/common.scss
  client/src/pages/SignUp.vue
  client/src/stores/category-store.ts
Labels: FE

#89 * 선호 음식 조사 로직 구성 완료
  client/src/components/sign-up/PreferredFoodCheck.vue
  client/src/stores/category-store.ts
Labels: FE

#90 Be feat/user preferred food
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/member/user/dto/user.input.ts
  sub-server-graphql/src/member/user/model/user.model.ts
  sub-server-graphql/src/member/user/user.service.ts
  sub-server-graphql/src/shared/models/user-category-mapping.model.ts
Labels: BE

#91 * 화면 전체 css 수정
  client/quasar.config.js
  client/src/css/common.scss
  client/src/css/layout.scss
  client/src/layouts/MainLayout.vue
  client/src/pages/Home.vue
  client/src/pages/Login.vue
  client/src/pages/SignUp.vue
  client/src/router/routes.ts
Labels: FE

#93 feat: 레시피 컨트롤러 테스트 코드 작성중
  server/src/test/java/choikang/MealGuard/recipe/controller/RecipeControllerTest.java
Labels: BE

#95 Fe feat/change main UI
  client/src/assets/fonts/Caveat-VariableFont_wght.ttf
  client/src/assets/fonts/QwitcherGrypen-Regular.ttf
  client/src/css/app.scss
  client/src/css/common.scss
  client/src/css/layout.scss
  client/src/pages/Home.vue
Labels: FE

#96 Fe feat/change main UI
  client/src/css/common.scss
  client/src/pages/Home.vue
Labels: FE
