Repository ChoiKang-TEAM/Meal-Guard, pull requests merged in 2023-07, with the labels that each got.

#20 Fix : 위도 경도를 격자로 변경하여 날씨를 가져오게 수정
  server/src/main/java/choikang/MealGuard/weather/controller/WeatherApiController.java
  server/src/main/java/choikang/MealGuard/weather/entity/Region.java
  server/src/main/java/choikang/MealGuard/weather/entity/Weather.java
  server/src/main/java/choikang/MealGuard/weather/helper/ConvertGPS.java
  server/src/main/java/choikang/MealGuard/weather/helper/LatXLngY.java
  server/src/main/java/choikang/MealGuard/weather/service/RegionService.java
  server/src/main/java/choikang/MealGuard/weather/service/WeatherApiService.java
Labels: Development, BE

#25 Fe feat/create meal guard css
  client/index.html
  client/quasar.config.js
  client/src/assets/images/cake.png
  client/src/assets/images/cake2.png
  client/src/assets/images/cake2_1.png
  client/src/assets/images/desserts.png
  client/src/assets/images/macaron.png
  client/src/boot/axios.ts
  client/src/common/constants.ts
  client/src/common/models.ts
  client/src/components/EssentialLink.vue
  client/src/components/RecipeTableDialog.vue
  client/src/components/models.ts
  client/src/composables/useIntersectionObserver.ts
  client/src/css/common.scss
  client/src/layouts/MainLayout.vue
  client/src/pages/Home.vue
  client/src/stores/food-store.ts
Labels: FE

#27 * 레시피 조합 정보 ui 작업
  client/package.json
  client/src/assets/images/picture1.png
  client/src/assets/images/picture10.png
  client/src/assets/images/picture11.png
  client/src/assets/images/picture2.png
  client/src/assets/images/picture3.png
  client/src/assets/images/picture4.png
  client/src/assets/images/picture5.png
  client/src/assets/images/picture6.png
  client/src/assets/images/picture7.png
  client/src/assets/images/picture8.png
  client/src/assets/images/picture9.png
  client/src/common/images.ts
  client/src/components/RecipeTableDialog.vue
  client/src/css/common.scss
  client/src/css/quasar.variables.scss
  client/src/pages/Home.vue
  client/src/stores/food-store.ts
  client/yarn.lock
Labels: FE

#28 * axios 구현
  client/src/boot/axios.ts
  sub-server-graphql/package.json
  sub-server-graphql/src/search/search-img.service.ts
  sub-server-graphql/yarn.lock
Labels: BE

#30 Be feat/sign up user
  sub-server-graphql/package.json
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/app.module.ts
  sub-server-graphql/src/app.service.ts
  sub-server-graphql/src/member/user/dto/user.input.ts
  sub-server-graphql/src/member/user/model/user.model.ts
  sub-server-graphql/src/member/user/user.module.ts
  sub-server-graphql/src/member/user/user.resolver.ts
  sub-server-graphql/src/member/user/user.service.ts
  sub-server-graphql/src/shared/auth/auth.module.ts
  sub-server-graphql/src/shared/auth/auth.resolver.ts
  sub-server-graphql/src/shared/auth/auth.service.ts
  sub-server-graphql/src/shared/auth/dto/auth-user.input.ts
  sub-server-graphql/src/shared/auth/jwt.strategy.ts
  sub-server-graphql/src/shared/interfaces/factory.interface.ts
  sub-server-graphql/src/shared/prisma/prisma.module.ts
  sub-server-graphql/src/shared/prisma/prisma.service.ts
  sub-server-graphql/src/shared/public-api/search/search-img.module.ts
  sub-server-graphql/src/shared/public-api/search/search-img.resolver.ts
  sub-server-graphql/src/shared/public-api/search/search-img.service.ts
  sub-server-graphql/yarn.lock
Labels: BE

#31 Be feat/sign up user
  sub-server-graphql/package.json
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/member/user/user.resolver.ts
  sub-server-graphql/src/member/user/user.service.ts
  sub-server-graphql/yarn.lock
Labels: BE

#32 * 로그인 기능 완료
  client/.eslintrc.cjs
  client/package.json
  client/src/boot/axios.ts
  client/src/common/models.ts
  client/src/composables/interceptor.ts
  client/src/graphql/member-user.ts
  client/src/pages/Login.vue
  client/src/router/index.ts
  client/src/router/routes.ts
  client/src/stores/auth-store.ts
  client/src/stores/index.ts
  client/src/stores/member-user-store.ts
  client/yarn.lock
Labels: FE

#33 * 좋아요 기능 api 요청
  client/src/boot/axios.ts
  client/src/boot/common.ts
  client/src/components/SignUp.vue
  client/src/pages/Home.vue
  client/src/pages/Login.vue
  client/src/stores/food-store.ts
Labels: FE

#34 * 토큰 값에 userSeq 추가
  sub-server-graphql/src/member/user/model/user.model.ts
  sub-server-graphql/src/shared/auth/auth.service.ts
Labels: BE

#36 Feat: 좋아요 하기,취소 구현
  server/src/main/java/choikang/MealGuard/recipe/controller/RecipeController.java
  server/src/main/java/choikang/MealGuard/recipe/entity/Favorite.java
  server/src/main/java/choikang/MealGuard/recipe/entity/Recipe.java
  server/src/main/java/choikang/MealGuard/recipe/repository/RecipeRepository.java
  server/src/main/java/choikang/MealGuard/recipe/service/RecipeService.java
Labels: Development, BE

#37 Fe feat/auth sign up
  client/quasar.config.js
  client/src/assets/images/login-icon.png
  client/src/boot/axios.ts
  client/src/common/columns.ts
  client/src/common/models.ts
  client/src/components/login/SignUp.vue
  client/src/components/recipe/RecipeTableDialog.vue
  client/src/css/common.scss
  client/src/pages/Home.vue
  client/src/pages/Login.vue
  client/src/pages/recipe/RecipeDetail.vue
  client/src/router/routes.ts
  client/src/stores/food-store.ts
Labels: FE

#38 Feat: 좋아요한 레시피를 보는 기능 구현
  server/build.gradle
  server/src/main/java/choikang/MealGuard/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/choikang/MealGuard/global/exception/ExceptionCode.java
  server/src/main/java/choikang/MealGuard/global/response/ErrorResponse.java
  server/src/main/java/choikang/MealGuard/helper/JwtUtils.java
  server/src/main/java/choikang/MealGuard/recipe/controller/RecipeController.java
  server/src/main/java/choikang/MealGuard/recipe/dto/FavoriteRecipeResponse.java
  server/src/main/java/choikang/MealGuard/recipe/repository/FavoriteRepository.java
  server/src/main/java/choikang/MealGuard/recipe/repository/RecipeRepository.java
  server/src/main/java/choikang/MealGuard/recipe/service/RecipeService.java
Labels: Development, BE

#39 * 메인 레이아웃 수정 중
  client/src/layouts/MainLayout.vue
  client/src/pages/Home.vue
Labels: FE

#41 * 레시피 디테일 페이지 수정 중
  client/.eslintrc.cjs
  client/src/boot/axios.ts
  client/src/common/models.ts
  client/src/css/common.scss
  client/src/layouts/HeaderLayout.vue
  client/src/pages/Home.vue
  client/src/pages/recipe/Recipe.vue
  client/src/pages/recipe/RecipeDetail.vue
  client/src/router/routes.ts
  client/src/stores/food-store.ts
  client/src/stores/recipe-store.ts
  client/src/stores/status-store.ts
Labels: FE

#42 * 헤더 및 중단 카드 작업
  client/src/layouts/HeaderLayout.vue
  client/src/pages/recipe/RecipeDetail.vue
Labels: FE

#43 * 나이 및 성별 추가 작업
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/member/user/dto/user.input.ts
  sub-server-graphql/src/member/user/model/user.model.ts
  sub-server-graphql/src/member/user/user.module.ts
  sub-server-graphql/src/member/user/user.service.ts
  sub-server-graphql/src/shared/auth/auth.service.ts
Labels: BE

#49 Fe feat/auth sign up
  client/package.json
  client/src/boot/axios.ts
  client/src/common/constants.ts
  client/src/common/models.ts
  client/src/components/recipe/RecipeTableDialog.vue
  client/src/css/common.scss
  client/src/pages/recipe/Recipe.vue
  client/src/pages/recipe/RecipeDetail.vue
  client/src/stores/food-store.ts
  client/src/stores/member-user-store.ts
  client/src/stores/recipe-store.ts
  client/src/stores/status-store.ts
  client/yarn.lock
Labels: FE

#51 * 블로그 연동 작업 중
  client/src/boot/axios.ts
  client/src/css/common.scss
  client/src/pages/recipe/Recipe.vue
  client/src/pages/recipe/RecipeDetail.vue
  client/src/stores/food-store.ts
  client/src/stores/naver-img-store.ts
Labels: FE

#52 Be feat/api/daum blog
  client/src/boot/axios.ts
  client/src/graphql/google-img-search.ts
  client/src/pages/recipe/RecipeDetail.vue
  client/src/stores/food-store.ts
  client/src/stores/naver-img-store.ts
  client/src/stores/recipe-store.ts
  sub-server-graphql/src/shared/public-api/search/model/search.model.ts
  sub-server-graphql/src/shared/public-api/search/search-img.resolver.ts
  sub-server-graphql/src/shared/public-api/search/search-img.service.ts
Labels: BE, FE

#54 Fe feat/recipe detail/card content UI
  client/src/components/recipe/RecipeBlogCard.vue
  client/src/css/common.scss
  client/src/pages/recipe/RecipeDetail.vue
  client/src/publish/PublishPage.vue
  client/src/publish/components/RecipeBlogCardComponent.vue
  client/src/router/routes.ts
Labels: FE

#55 * 퍼블리싱 연결
  client/src/boot/axios.ts
  client/src/common/models.ts
  client/src/components/recipe/RecipeBlogCard.vue
  client/src/css/common.scss
  client/src/pages/recipe/RecipeDetail.vue
Labels: FE

#56 * 블로그 카드 작업 완료
  client/src/components/recipe/RecipeBlogCard.vue
  client/src/css/common.scss
  client/src/layouts/HeaderLayout.vue
  client/src/pages/recipe/RecipeDetail.vue
  client/src/stores/food-store.ts
  client/src/stores/naver-img-store.ts
  client/src/stores/status-store.ts
Labels: FE

#57 * 블로그 데이터 가져오는 사이즈 변경
  sub-server-graphql/src/shared/public-api/search/search-img.service.ts
Labels: BE

#59 * 유저 가드 추가
  sub-server-graphql/package.json
  sub-server-graphql/src/member/user/user.resolver.ts
  sub-server-graphql/src/member/user/user.service.ts
  sub-server-graphql/src/shared/decorators/user.decorate.ts
  sub-server-graphql/src/shared/guard/jwt-auth.guard.ts
  sub-server-graphql/yarn.lock
Labels: BE

#61 * 선호 음식 로직 추가
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/member/category/category.module.ts
  sub-server-graphql/src/member/category/category.resolver.ts
  sub-server-graphql/src/member/category/category.service.ts
  sub-server-graphql/src/member/category/model/category.model.ts
  sub-server-graphql/src/member/user/user.service.ts
Labels: BE

#62 * 선호 음식 리스트 인풋 데이터 추가
  sub-server-graphql/src/member/user/dto/user.input.ts
Labels: BE

#64 Be feat/sign up user
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/app.module.ts
  sub-server-graphql/src/member/food/dto/food.input.ts
  sub-server-graphql/src/member/food/food.module.ts
  sub-server-graphql/src/member/food/food.service.ts
  sub-server-graphql/src/member/food/model/food.model.ts
  sub-server-graphql/src/member/user/user.service.ts
Labels: BE

#65 * 없는 음식에 대하여 신규 유저가 추가할 수 있게 설정
  sub-server-graphql/src/member/food/dto/food.input.ts
  sub-server-graphql/src/member/food/food.service.ts
Labels: BE

#66 Be feat/sign up user
  sub-server-graphql/src/member/category/category.service.ts
  sub-server-graphql/src/member/food/food.resolver.ts
Labels: BE

#67 * graphQL 쿼리 호출문 food, category 작성
  client/src/graphql/category.ts
  client/src/graphql/dto/food-input.ts
  client/src/graphql/food.ts
  client/src/stores/category-store.ts
  client/src/stores/food-store.ts
Labels: FE

#68 * 로그인 시 비밀번호 자동 입력 방지
  client/src/pages/Login.vue
Labels: FE

#69 * 비속어 필터링 적용
  sub-server-graphql/src/member/food/food.resolver.ts
  sub-server-graphql/src/member/food/food.service.ts
  sub-server-graphql/src/member/user/dto/user.input.ts
  sub-server-graphql/src/member/user/user.resolver.ts
  sub-server-graphql/src/shared/common-files/bad-word-list.txt
  sub-server-graphql/src/shared/pipes/language-filter.pipe.ts
Labels: BE

#70 Fe feat/sign up UI
  client/src/components/login/SignUp.vue
  client/src/stores/category-store.ts
Labels: FE

#71 * 회원가입 UI 수정 중
  client/src/components/login/SignUp.vue
Labels: FE
