Repository ChoiKang-TEAM/Meal-Guard, pull requests merged in 2023-06, with the labels that each got.

#5 Feat : 시간대별 맞춤 음식 추천 구현
  server/build.gradle
  server/src/main/java/choikang/MealGuard/food/controller/FoodController.java
  server/src/main/java/choikang/MealGuard/food/dto/FoodDto.java
  server/src/main/java/choikang/MealGuard/food/entity/Food.java
  server/src/main/java/choikang/MealGuard/food/entity/Time.java
  server/src/main/java/choikang/MealGuard/food/mapper/FoodMapper.java
  server/src/main/java/choikang/MealGuard/food/repository/FoodRepository.java
  server/src/main/java/choikang/MealGuard/food/service/FoodService.java
Labels: Development, BE

#8 * client 프로젝트 초기 생성
  client/.editorconfig
  client/.eslintignore
  client/.eslintrc.cjs
  client/.gitignore
  client/.npmrc
  client/.prettierrc
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/README.md
  client/index.html
  client/package.json
  client/postcss.config.cjs
  client/public/favicon.ico
  client/public/icons/favicon-128x128.png
  client/public/icons/favicon-16x16.png
  client/public/icons/favicon-32x32.png
  client/public/icons/favicon-96x96.png
  client/quasar.config.js
  client/src/App.vue
  client/src/assets/quasar-logo-vertical.svg
  client/src/boot/.gitkeep
  client/src/boot/axios.ts
  client/src/boot/i18n.ts
  client/src/components/EssentialLink.vue
  client/src/components/ExampleComponent.vue
  client/src/components/models.ts
  client/src/css/app.scss
  client/src/css/quasar.variables.scss
  client/src/env.d.ts
  client/src/i18n/en-US/index.ts
  client/src/i18n/index.ts
  client/src/layouts/MainLayout.vue
  client/src/pages/ErrorNotFound.vue
  client/src/pages/Home.vue
  client/src/quasar.d.ts
  client/src/router/index.ts
  client/src/router/routes.ts
  client/src/shims-vue.d.ts
  client/src/stores/example-store.ts
  client/src/stores/index.ts
  client/src/stores/store-flag.d.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#9 Feat : 기상청 api를 활용한 로직 구현
  server/src/main/java/choikang/MealGuard/weather/controller/RegionApiController.java
  server/src/main/java/choikang/MealGuard/weather/controller/WeatherApiController.java
  server/src/main/java/choikang/MealGuard/weather/dto/WeatherDto.java
  server/src/main/java/choikang/MealGuard/weather/entity/Region.java
  server/src/main/java/choikang/MealGuard/weather/entity/Weather.java
Labels: Development, BE

#10 Fix : 계층 변경 , 예외처리 로직 추가
  server/src/main/java/choikang/MealGuard/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/choikang/MealGuard/global/exception/BusinessLogicException.java
  server/src/main/java/choikang/MealGuard/global/exception/ExceptionCode.java
  server/src/main/java/choikang/MealGuard/global/exception/InternalServerErrorException.java
  server/src/main/java/choikang/MealGuard/global/response/ErrorResponse.java
  server/src/main/java/choikang/MealGuard/weather/controller/RegionApiController.java
  server/src/main/java/choikang/MealGuard/weather/controller/WeatherApiController.java
  server/src/main/java/choikang/MealGuard/weather/repository/RegionRepository.java
  server/src/main/java/choikang/MealGuard/weather/service/RegionService.java
  server/src/main/java/choikang/MealGuard/weather/service/WeatherApiService.java
Labels: Refector, BE

#11 fix: 경로 잘못 되어있던거 수정
  server/src/main/java/choikang/MealGuard/config/SecurityConfiguration.java
Labels: BE

#12 Feat : 위도와 경도 전달시 가까운 지역과 온도를 응답받게 설정
  server/src/main/java/choikang/MealGuard/weather/controller/WeatherApiController.java
  server/src/main/java/choikang/MealGuard/weather/dto/WeatherDto.java
  server/src/main/java/choikang/MealGuard/weather/service/RegionService.java
  server/src/main/java/choikang/MealGuard/weather/service/WeatherApiService.java
Labels: Development, BE

#13 * 밀가드 프론트엔드 작업 중
  client/.eslintrc.cjs
  client/.prettierrc
  client/.vscode/settings.json
  client/quasar.config.js
  client/src/components/EssentialLink.vue
  client/src/layouts/MainLayout.vue
  client/src/pages/Home.vue
Labels: FE

#14 Be feat/sub server create
  .DS_Store
  sub-server-graphql/.eslintrc.js
  sub-server-graphql/.gitignore
  sub-server-graphql/.prettierrc
  sub-server-graphql/README.md
  sub-server-graphql/nest-cli.json
  sub-server-graphql/package.json
  sub-server-graphql/src/app.controller.spec.ts
  sub-server-graphql/src/app.controller.ts
  sub-server-graphql/src/app.module.ts
  sub-server-graphql/src/app.service.ts
  sub-server-graphql/src/main.ts
  sub-server-graphql/test/app.e2e-spec.ts
  sub-server-graphql/test/jest-e2e.json
  sub-server-graphql/tsconfig.build.json
  sub-server-graphql/tsconfig.json
  sub-server-graphql/yarn.lock
Labels: BE

#15 Feat : 네이버 블로그 끌어오는 api , 앤드포인트 구현
  server/src/main/java/choikang/MealGuard/blog/component/NaverBlogSearchApi.java
  server/src/main/java/choikang/MealGuard/blog/controller/NaverBlogController.java
  server/src/main/java/choikang/MealGuard/blog/dto/NaverBlogDto.java
Labels: Development, BE

#16 프론트에서 이미지 뿌려지게 설정
  client/package.json
  client/quasar.config.js
  client/src/boot/common.ts
  client/src/graphql/google-img-search.ts
  client/src/pages/ErrorNotFound.vue
  client/src/pages/Home.vue
  client/src/stores/google-img-store.ts
  client/tsconfig.json
  client/yarn.lock
  sub-server-graphql/.eslintrc.js
  sub-server-graphql/.gitignore
  sub-server-graphql/.prettierrc
  sub-server-graphql/.vscode/settings.json
  sub-server-graphql/package.json
  sub-server-graphql/prisma/schema.prisma
  sub-server-graphql/src/app.controller.spec.ts
  sub-server-graphql/src/app.controller.ts
  sub-server-graphql/src/app.module.ts
  sub-server-graphql/src/app.service.ts
  sub-server-graphql/src/main.ts
  sub-server-graphql/src/prisma/prisma.module.ts
  sub-server-graphql/src/prisma/prisma.service.ts
  sub-server-graphql/src/search/search-img.module.ts
  sub-server-graphql/src/search/search-img.resolver.ts
  sub-server-graphql/src/search/search-img.service.ts
  sub-server-graphql/yarn.lock
Labels: Development, BE, FE

#17 글꼴 및 기타 ui 적용
  client/index.html
  client/public/Meal-Guard-Favicon.ico
  client/public/favicon.ico
  client/public/icons/Meal-Guard-Favicon.png
  client/public/icons/favicon-128x128.png
  client/public/icons/favicon-16x16.png
  client/public/icons/favicon-32x32.png
  client/public/icons/favicon-96x96.png
  client/src/assets/fonts/NeoDunggeunmoPro-Regular.woff
  client/src/components/EssentialLink.vue
  client/src/components/ExampleComponent.vue
  client/src/css/app.scss
  client/src/layouts/MainLayout.vue
  client/src/pages/member-user/ChatMessenger.vue
  client/src/pages/member-user/MemberUser.vue
  client/src/router/routes.ts
Labels: FE
